name: Validar Compilación y Docker

on: [push]

jobs:
  test-go:
    name: Comprobación de compilación de código
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-go
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Pruebas unitarias
      run: go test -cover

  docker-build-check:
    name: Comprobación con docker/build y docker/bake
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx (Herramienta de Bake y Build)
        uses: docker/setup-buildx-action@v3

      - name: Validación de compilación (docker/build)
        uses: docker/build-push-action@v5
        with:
          context: ./backend-go
          push: false # Solo comprueba que compila, no la sube (validación)
          tags: alandpm/app-go:test